Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 11635
Internal Server Error: /organism_card
Traceback (most recent call last):
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\views\generic\list.py", line 154, in get
    self.object_list = self.get_queryset()
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\project\adjCOADD\apputil\utils.py", line 182, in get_queryset
    self.filterset = self.filterset_class(self.request.GET, queryset=queryset)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\project\adjCOADD\dorganism\utils.py", line 81, in __init__
    print(f"in filter __init__: {self.filters[i].count()} : {i}")
                                 ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ChoiceFilter' object has no attribute 'count'
"GET /organism_card HTTP/1.1" 500 94495
Internal Server Error: /organism_card
Traceback (most recent call last):
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\views\generic\list.py", line 154, in get
    self.object_list = self.get_queryset()
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\project\adjCOADD\apputil\utils.py", line 182, in get_queryset
    self.filterset = self.filterset_class(self.request.GET, queryset=queryset)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\project\adjCOADD\dorganism\utils.py", line 81, in __init__
    print(f"in filter __init__: {self.filters[i].count()} : {i}")
                                 ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ChoiceFilter' object has no attribute 'count'
"GET /organism_card HTTP/1.1" 500 94515
Internal Server Error: /organism_card
Traceback (most recent call last):
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\views\generic\list.py", line 154, in get
    self.object_list = self.get_queryset()
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\project\adjCOADD\apputil\utils.py", line 182, in get_queryset
    self.filterset = self.filterset_class(self.request.GET, queryset=queryset)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\project\adjCOADD\dorganism\utils.py", line 81, in __init__
    print(f"in filter __init__: {self.filters[i]} : {Organism.objects.filter(i=Dictionary.objects.filter(dict_class=Organism.Choice_Dictionary[i][0])).count()}")
                                                                                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
KeyError: 'Class'
"GET /organism_card HTTP/1.1" 500 94443
Internal Server Error: /organism_card
Traceback (most recent call last):
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\views\generic\list.py", line 154, in get
    self.object_list = self.get_queryset()
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\project\adjCOADD\apputil\utils.py", line 182, in get_queryset
    self.filterset = self.filterset_class(self.request.GET, queryset=queryset)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\project\adjCOADD\dorganism\utils.py", line 81, in __init__
    test_i=Organism.objects.filter(oxygen_pref__icontains=Dictionary.objects.filter(dict_class=Organism.Choice_Dictionary[i][0])).count()
                                                                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
KeyError: 'Class'
"GET /organism_card HTTP/1.1" 500 95261
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 11635
Internal Server Error: /organism_card
Traceback (most recent call last):
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\views\generic\list.py", line 154, in get
    self.object_list = self.get_queryset()
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\project\adjCOADD\apputil\utils.py", line 182, in get_queryset
    self.filterset = self.filterset_class(self.request.GET, queryset=queryset)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\project\adjCOADD\dorganism\utils.py", line 81, in __init__
    test_i=Organism.objects.filter(oxygen_pref__icontains='Aerobic').count() #Dictionary.objects.filter(dict_class=Organism.Choice_Dictionary[i][0])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\db\models\query.py", line 1421, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\db\models\query.py", line 1439, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\db\models\query.py", line 1446, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\db\models\sql\query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\db\models\sql\query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\db\models\sql\query.py", line 1478, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\db\models\sql\query.py", line 1292, in build_lookup
    raise FieldError(
django.core.exceptions.FieldError: Related Field got invalid lookup: icontains
"GET /organism_card HTTP/1.1" 500 138299
Internal Server Error: /organism_card
Traceback (most recent call last):
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\views\generic\list.py", line 154, in get
    self.object_list = self.get_queryset()
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\project\adjCOADD\apputil\utils.py", line 182, in get_queryset
    self.filterset = self.filterset_class(self.request.GET, queryset=queryset)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\project\adjCOADD\dorganism\utils.py", line 81, in __init__
    test_i=Organism.objects.filter(oxygen_pref__icontains='Aerobic').count() #Dictionary.objects.filter(dict_class=Organism.Choice_Dictionary[i][0])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\db\models\query.py", line 1421, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\db\models\query.py", line 1439, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\db\models\query.py", line 1446, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\db\models\sql\query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\db\models\sql\query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\db\models\sql\query.py", line 1478, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uqwzhon4\Anaconda3\envs\orgdb_env\Lib\site-packages\django\db\models\sql\query.py", line 1292, in build_lookup
    raise FieldError(
django.core.exceptions.FieldError: Related Field got invalid lookup: icontains
"GET /organism_card HTTP/1.1" 500 138299
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 11635
"GET /static/images/AMD00003.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00004.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00002.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00015.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00017.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00018.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00023.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00021.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00010.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00025.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00179.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00012.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00219.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00024.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00022.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00027.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00020.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00014.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00216.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00011.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00019.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00026.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00016.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00013.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00005.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00006.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00007.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00008.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00009.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00178.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00028.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00030.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00029.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00032.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00031.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00033.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00220.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00035.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00034.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00036.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00214.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00037.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00039.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00038.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00040.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00041.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00043.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00042.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00044.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00045.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00003.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00002.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00216.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00014.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00013.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00025.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00023.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00026.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00012.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00016.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00027.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00020.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00179.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00017.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00018.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00021.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00022.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00010.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00019.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00024.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00011.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00219.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00009.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00015.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00004.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00005.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00007.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00008.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00006.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00178.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00028.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00029.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00033.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00032.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00031.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00030.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00034.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00035.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00036.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00037.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00214.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00220.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00038.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00039.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00041.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00040.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00043.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00044.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00042.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00002.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00003.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00004.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00011.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00016.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00219.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00012.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00020.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00014.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00024.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00010.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00017.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00026.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00021.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00025.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00022.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00023.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00216.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00013.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00027.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00179.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00019.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00018.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00015.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00006.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00007.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00005.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00178.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00008.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00009.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00028.svg HTTP/1.1" 404 1917
"GET /static/images/AMD00029.svg HTTP/1.1" 404 1917
